version: 1
validation: sovereign
default_denom: kud
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000kud
- name: bob
  coins:
  - 10000token
  - 100000000kud
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000kud
- name: validator1
  bonded: 200000000kud
- name: validator2
  bonded: 100000000kud